sudo: required

language: java

services:
  - docker

before_install:
  - docker build -t ladder-db:latest technical-details/docker/db/.
  - cd technical-details/docker/db-test && docker-compose up -d && cd ../../..

after_success:
  - mvn clean test jacoco:report coveralls:report