sudo: required

language: java

services:
  - docker

before_install:
  - cd technical-details/docker/db && docker build -t ladder-db:latest .
  - cd technical-details/docker/db-test && docker-compose up -d

after_success:
  - mvn clean test jacoco:report coveralls:report